#pragma once

#include <cstdarg>
#include <initializer_list>
#include <string>
#include <vector>
namespace rmdb {
enum class RC_VALUES {
  RC_SUCCESS = 0,
  RC_DISK_MANAGER_NO_FILE,
  RC_DISK_MANAGER_EXISTS_FILE,
  RC_DISK_MANAGER_WRITE_PAGE_ERROR,
  RC_DISK_MANAGER_READ_PAGE_ERROR,
  RC_BUFFER_POOL_MANAGER_UNPIN_ERROR,
  RC_BUFFER_POOL_MANAGER_PIN_ERROR,
  RC_BUFFER_POOL_MANAGER_DELETE_PAGE_ERROR,
  RC_BUFFER_POOL_MANAGER_NEW_PAGE_ERROR,
  RC_BUFFER_POOL_MANAGER_UPDATE_PAGE_ERROR,
  RC_BUFFER_POOL_MANAGER_FETCG_PAGE_ERROR,
  RC_SM_MANAGER_EXISTS_DB,
  RC_SM_MANAGER_NO_DB,
  RC_SM_MANAGER_EXISTS_TABLE,
  RC_SM_MANAGER_NO_TABLE,
  RC_SM_MANAGER_EXISTS_INDEX,
  RC_SM_MANAGER_NO_INDEX,
  RC_SM_MANAGER_ERROR,
  RC_LOCK_MANAGER_SHARED_LOCK_ERROR,
  RC_LOCK_MANAGER_EXCLUSIVE_LOCK_ERROR,
  RC_LOCK_MANAGER_IS_ERROR,
  RC_LOCK_MANAGER_IX_ERROR,
  RC_LOCK_MANAGER_UNLOCK_ERROR,
  RC_TRANSACTION_GET_ERROR,
  RC_TRANSACTION_EXECUTE_ERROR,
  RC_TRANSACTION_COMMIT_ERROR,
  RC_TRANSACTION_ABORT_ERROR,
  RC_LRU_REPLACER_VICTIM_ERROR,
  RC_LRU_REPLACER_PIN_ERROR,
  RC_LRU_REPLACER_UNPIN_ERROR,
  RC_LOG_MANAGER_SERIALIZE_ERROR,
  RC_LOG_MANAGER_DESERIALIZE_ERROR,
  RC_LOG_MANAGER_DELETE_LOG_ERROR,
  RC_LOG_MANAGER_UPDATE_LOG_ERROR,
  RC_LOG_RECOVERY_REDO_ERROR,
  RC_LOG_RECOVERY_UNDO_ERROR,
  RC_RM_FILE_HANDLE_INSERT_RECORD_ERROR,
  RC_RM_FILE_HANDLE_DELETE_RECORD_ERROR,
  RC_RM_FILE_HANDLE_UDPATE_RECORD_ERROR,
  RC_RM_FILE_HANDLE_CREATE_NEW_PAGE_HANDLE_ERROR,
  RC_PLANNER_LIGICAL_ERROR,
  RC_PLANNER_PHYSICAL_ERROR,
  RC_PLANNER_GENERATE_ERROR,
  RC_PLANNER_MAKE_ONE_REL_ERROR,
  RC_IX_SCAN_ERROR,
  RC_IX_INDEX_HANDLE_ERROR,
  RC_IX_NODE_ERROR,
  RC_EXECUTION_MANAGER_ERROR,
  RC_ANALYZE_CHECK_COLUMN_ERROR,
  RC_ANALYZE_GET_ALL_COLS_ERROR,
  RC_ANALYZE_GET_CLAUSE_ERROR,
  RC_ANALYZE_CHECK_CLAUSE_ERROR,
  RC_ANALYZE_CONVERT_SV_VALUE_ERROR,
  RC_ANALYZE_CONVERT_SV_COMP_OP_ERROR,
  RC_UNIX_ERROR,
};

#define ENUM_TO_STRING(ENUM) #ENUM

const std::vector<std::string> ERROR_STR = {
    ENUM_TO_STRING(RC_SUCCESS),
    ENUM_TO_STRING(RC_DISK_MANAGER_NO_FILE),
    ENUM_TO_STRING(RC_DISK_MANAGER_EXISTS_FILE),
    ENUM_TO_STRING(RC_DISK_MANAGER_WRITE_PAGE_ERROR),
    ENUM_TO_STRING(RC_DISK_MANAGER_READ_PAGE_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_UNPIN_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_PIN_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_DELETE_PAGE_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_NEW_PAGE_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_UPDATE_PAGE_ERROR),
    ENUM_TO_STRING(RC_BUFFER_POOL_MANAGER_FETCG_PAGE_ERROR),
    ENUM_TO_STRING(RC_SM_MANAGER_EXISTS_DB),
    ENUM_TO_STRING(RC_SM_MANAGER_NO_DB),
    ENUM_TO_STRING(RC_SM_MANAGER_EXISTS_TABLE),
    ENUM_TO_STRING(RC_SM_MANAGER_NO_TABLE),
    ENUM_TO_STRING(RC_SM_MANAGER_EXISTS_INDEX),
    ENUM_TO_STRING(RC_SM_MANAGER_NO_INDEX),
    ENUM_TO_STRING(RC_SM_MANAGER_ERROR),
    ENUM_TO_STRING(RC_LOCK_MANAGER_SHARED_LOCK_ERROR),
    ENUM_TO_STRING(RC_LOCK_MANAGER_EXCLUSIVE_LOCK_ERROR),
    ENUM_TO_STRING(RC_LOCK_MANAGER_IS_ERROR),
    ENUM_TO_STRING(RC_LOCK_MANAGER_IX_ERROR),
    ENUM_TO_STRING(RC_LOCK_MANAGER_UNLOCK_ERROR),
    ENUM_TO_STRING(RC_TRANSACTION_GET_ERROR),
    ENUM_TO_STRING(RC_TRANSACTION_EXECUTE_ERROR),
    ENUM_TO_STRING(RC_TRANSACTION_COMMIT_ERROR),
    ENUM_TO_STRING(RC_TRANSACTION_ABORT_ERROR),
    ENUM_TO_STRING(RC_LRU_REPLACER_VICTIM_ERROR),
    ENUM_TO_STRING(RC_LRU_REPLACER_PIN_ERROR),
    ENUM_TO_STRING(RC_LRU_REPLACER_UNPIN_ERROR),
    ENUM_TO_STRING(RC_LOG_MANAGER_SERIALIZE_ERROR),
    ENUM_TO_STRING(RC_LOG_MANAGER_DESERIALIZE_ERROR),
    ENUM_TO_STRING(RC_LOG_MANAGER_DELETE_LOG_ERROR),
    ENUM_TO_STRING(RC_LOG_MANAGER_UPDATE_LOG_ERROR),
    ENUM_TO_STRING(RC_LOG_RECOVERY_REDO_ERROR),
    ENUM_TO_STRING(RC_LOG_RECOVERY_UNDO_ERROR),
    ENUM_TO_STRING(RC_RM_FILE_HANDLE_INSERT_RECORD_ERROR),
    ENUM_TO_STRING(RC_RM_FILE_HANDLE_DELETE_RECORD_ERROR),
    ENUM_TO_STRING(RC_RM_FILE_HANDLE_UDPATE_RECORD_ERROR),
    ENUM_TO_STRING(RC_RM_FILE_HANDLE_CREATE_NEW_PAGE_HANDLE_ERROR),
    ENUM_TO_STRING(RC_PLANNER_LIGICAL_ERROR),
    ENUM_TO_STRING(RC_PLANNER_PHYSICAL_ERROR),
    ENUM_TO_STRING(RC_PLANNER_GENERATE_ERROR),
    ENUM_TO_STRING(RC_PLANNER_MAKE_ONE_REL_ERROR),
    ENUM_TO_STRING(RC_IX_SCAN_ERROR),
    ENUM_TO_STRING(RC_IX_INDEX_HANDLE_ERROR),
    ENUM_TO_STRING(RC_IX_NODE_ERROR),
    ENUM_TO_STRING(RC_EXECUTION_MANAGER_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_CHECK_COLUMN_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_GET_ALL_COLS_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_GET_CLAUSE_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_CHECK_CLAUSE_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_CONVERT_SV_VALUE_ERROR),
    ENUM_TO_STRING(RC_ANALYZE_CONVERT_SV_COMP_OP_ERROR),
    ENUM_TO_STRING(RC_UNIX_ERROR),
};

inline std::string strrc(enum RC_VALUES rc) {
  return ERROR_STR[static_cast<int>(rc)];
}

enum class LOG_MODES {
  info,
  debug,
  warning,
  error,
};

#define LOG_WARNING(format, ...)                                               \
  printf("Warning:   ");                                                       \
  printf(format, __VA_ARGS__);                                                 \
  printf("\n");
#define LOG_ERROR(format, ...)                                                 \
  printf("Error:      ");                                                      \
  printf(format, __VA_ARGS__);                                                 \
  printf("\n");
#define LOG_INFO(format, ...)                                                  \
  printf("Info:       ");                                                      \
  printf(format, __VA_ARGS__);                                                 \
  printf("\n");
#define LOG_DEBUG(format, ...)                                                 \
  printf("Debug:      ");                                                      \
  printf(format, __VA_ARGS__);                                                 \
  printf("\n");

}; // namespace rmdb
